apiVersion : apps/v1
kind: Deployment
metadata:
  name: djangoapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangoapp
  template:
    metadata:
      labels:
        app: djangoapp 
    spec:
      containers:
        - name: djangoapp 
          image: akscrg.azurecr.io/djangoapp
          ports:
          - containerPort: 8000
